#!/bin/bash

cd ~

#Chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

sudo apt update
sudo apt install -y curl git google-chrome-stable python3-pip python3-tk vim synapse tmux xclip

#Dotfiles
git clone https://github.com/mkoo21/dotfiles.git
sudo ln -sf dotfiles/.vimrc .vimrc
sudo ln -sf dotfiles/.bashrc .bashrc
sudo ln -sf dotfiles/.bash_aliases .bash_aliases
sudo ln -sf dotfiles/.tmux.conf .tmux.conf

#Setup ssh agent (change if not putting .ssh in home?)
echo "Set up ssh-agent:"
ssh-keygen -t rsa -b 4096 -C "koo.martin@gmail.com"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

#Setup vim 
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#VSCode
curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
sudo apt install -y code

#NodeJS
curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install -y nodejs build-essential
rm nodesource_setup.sh
#Put node modules somewhere that doesn't require sudo
npm config set prefix ~/npm

#Archey 
wget https://github.com/downloads/djmelik/archey/archey-0.2.8.deb
sudo apt install -y scrot lsb-release
sudo dpkg -i archey-0.2.8.deb
rm archey-0.2.8.deb

#Scala (optional bc HUEG)
#sudo apt install -y scala
#echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
#sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
#sudo apt-get update
#sudo apt-get install sbt

#Intellij (replace with latest ver?)
#Setup manually by running /opt/idea-IC*/bin/idea.sh
#wget https://download.jetbrains.com/idea/ideaIC-2018.1.2.tar.gz
#sudo tar xf ideaIC-2018.1.2.tar.gz -C /opt/

#Mate preferences
#sudo apt install dconf-tools
#dconf write /org/mate/terminal/global/ctrl-tab-switch-tabs true
#mate-terminal --load-config ~/dotfiles/mate/martin-config

#You are done!
source ~/.bashrc
cd -
