#!/usr/bin/python

import os
import sys
import subprocess

from typing import TypedDict

from enum import Enum

class Options(TypedDict):
    InputPath: str

def run_command(command):
    result = subprocess.run(command)

    # forward output
    if result.stdout:
        print(result.stdout, end='')

    if result.stderr:
        print(result.stderr, end='', file=sys.stderr)
    # exit if fail
    if result.returncode != 0:
        sys.exit(result.returncode)

def check_arguments():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <input_path>", file=sys.stderr)
        sys.exit(1)

def decrypt(opts: Options):
    command = ["gpg", opts["InputPath"]]
    run_command(command)

if __name__ == "__main__":
    check_arguments()

    opts: Options = { 
        "InputPath": sys.argv[1],
    }
    decrypt(opts)
