#!/usr/bin/env python3

import os 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from subprocess import run, PIPE
from io import StringIO

p = run(["git", "log", "--pretty=format:\"%h%x09%an%x09%ad\""], stdout=PIPE)
df = pd.read_csv(StringIO(p.stdout.decode('utf-8')), sep="\t+", names=['commit', 'author', 'date'])
df = df.dropna() #Exist commits w/o author, etc
df['date'] = pd.to_datetime(df.date.apply(lambda x: x[:-1]))
df['datetuple'] = df.date.apply(lambda x: (x.year, x.month, x.day))

freqs = df[['commit', 'datetuple']].groupby('datetuple').agg(np.size)
n, bins, patches = plt.hist(freqs.commit.values, freqs.shape[0])
plt.show()
