#!/usr/bin/python

import os
import sys
import subprocess

def check_arguments():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_path> <output_path>", file=sys.stderr)
        sys.exit(1)

def check_paths(opts):
    input_path = opts["inputPath"]
    # directories need to be archived prior
    if os.path.isdir(input_path):
        tar_out_path = f"{input_path}.tar.gz"
        command = ["tar", "-czf", tar_out_path, input_path] # test
        run_command(command)
        opts["tarInPath"] = True
        opts["archiveCreated"] = True

def run_command(command):
    result = subprocess.run(command)

    # forward output
    if result.stdout:
        print(result.stdout, end='')

    if result.stderr:
        print(result.stderr, end='', file=sys.stderr)
    # exit if fail
    if result.returncode != 0:
        sys.exit(result.returncode)

if __name__ == "__main__":
    check_arguments()

    opts = { 
        "cleanupInputPath": False,
        "inputPath": sys.argv[1],
        "outputPath": sys.argv[2],
        "archiveCreated": False
    }
    check_paths(opts)